# Generated by Django 3.2.3 on 2021-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Great'), ('C', 'Above Average'), ('D', 'Average'), ('E', 'Mediocre'), ('F', 'Failure')], default='A', max_length=1)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
    ]
